# Generated by Django 4.1.5 on 2023-01-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('dueDate', models.DateField(auto_now_add=True)),
                ('priority', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
