# Generated by Django 4.1.5 on 2023-01-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dueDate',
            field=models.DateField(),
        ),
    ]
